{#- Snowcap dbt Governance Macros -#}
{#- Generated by: snowcap generate dbt-macros -#}
{#- Documentation: https://snowcap.datacoves.com -#}

{% macro snowcap_apply_policies() %}
  {{ snowcap_apply_masking_tags() }}
  {{ snowcap_apply_row_access_policy() }}
{% endmacro %}

{% macro snowcap_apply_masking_tags() %}
  {% set tag_db = var('snowcap_tag_database', target.database) %}
  {% set tag_schema = var('snowcap_tag_schema', 'TAGS') %}
  {% set columns = model.columns.values() if model.columns else [] %}

  {% for column in columns %}
    {% set meta = column.meta if column.meta else {} %}
    {% set masking_tag = meta.get('masking_tag') %}

    {% if masking_tag %}
      ALTER TABLE {{ this }} MODIFY COLUMN {{ adapter.quote(column.name) }}
        SET TAG {{ tag_db }}.{{ tag_schema }}.{{ masking_tag }} = 'true';
    {% endif %}
  {% endfor %}
{% endmacro %}

{% macro snowcap_apply_row_access_policy() %}
  {% set meta = config.get('meta', {}) %}
  {% set policy = meta.get('row_access_policy') %}
  {% set column = meta.get('row_access_column') %}
  {% set policy_db = var('snowcap_policy_database', target.database) %}
  {% set policy_schema = var('snowcap_policy_schema', 'POLICIES') %}

  {% if policy and column %}
    ALTER TABLE {{ this }} ADD ROW ACCESS POLICY
      {{ policy_db }}.{{ policy_schema }}.{{ policy }} ON ({{ column }});
  {% endif %}
{% endmacro %}
